pull_request_rules:
  - name: Automatic merge on approval and complete CI checks
    conditions:
      - "#approved-reviews-by>=1"
      - "check-success=CI/CD"
      - "check-success=codecov/changes"
      - "check-success=codecov/patch"
      - "check-success=codecov/project"
      - label!=DO NOT MERGE
      - base=master
      - or:
          - head~=^hotfix/
          - head~=^feature/
    actions:
      merge:
        method: merge
  - name: Automatic on complete CI checks
    conditions:
      - "check-success=CI/CD / build (16.x) (pull_request)"
      - "check-success=codecov/changes"
      - "check-success=codecov/patch"
      - "check-success=codecov/project"
      - label!=DO NOT MERGE
      - base=master
      - or:
          - head~=^hotfix/
          - head~=^feature/
    actions:
      merge:
        method: merge
